### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by JenniferLicht** [KpdsK/mercado-liebre#1]
**1. Respecto a la estructura del sitio visualizar que contenga estos elementos cada sección**
Cumple

**2. Haciendo foco en los estilos del pie de página (Footer):**
Cumple

**3. ¿El sitio se adapta a distintas resoluciones de pantalla?**
Cumple

**4. ¿El sitio cuenta con un formulario de registro de usuarios?**
Cumple

**5. ¿El sitio cuenta con un formulario de login?**
Cumple

**7. ¿El search bar es un formulario?**
Cumple

**8. ¿Se utilizan animaciones y propiedades de transición de CSS?**
Cumple. 

**9. Para terminar el feedback, menciona algunas cosas que crees que tu compañero hizo bien.**
Cumple con todos los elementos requeridos en su correspondiente orden y ubicación respecto al resto.

**10. Por último, menciona algo que tu compañero podría mejorar.**
La barra de navegación no es navegable, por lo que no se puede acceder a las otras secciones por los que deberían ser botones; sin embargo, si se puede acceder a esas secciones por la URL. Además, el formulario de registro y del login no tienen una hoja de estilos. Y faltan algunas faltas de ortografía como letras demás (por ejemplo _Interesess_ o _correo electronico_ en el form de register)

**Comment by KpdsK** [comment]
Sobre el ítem 10
*) La barra de navegación, SI, es navegable, al menos en los 2 enlaces que debería tener (según requerimientos), crear una cuenta (registro) e ingreso (login). Se desestima.
*) Las paginas que contienen el formularios de registro y el login, SI, tienen estilos, solo que están en un solo archivo para toda la web. Se desestima.
*) Correcciones ortográficas en las palabras indicadas, y en otras detectadas. Solucionado
